language: node_js
node_js: 
  - "stable"
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - mocha ../api/src/**/*.test.js --recursive --require @babel/register --timeout 10000 --exit